branches:
  only:
    - master

matrix:
  include:
    - language: android
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
      android: 
        components:
          - platform-tools
          - build-tools-27.1.7
          - android-27
      env: LANE='android'

    - language: objective-c
      os: osx
      env : LANE='ios'